### ISSUE TITLE
The keybinding is no demonstrated  clearly.

### ISSUE THREAD

**Issue by FireSK7** [anuvyklack/pretty-fold.nvim#19]
also, it conflicts with my original key binding, it could be much better if the keybinding is more customizable.

**Comment by jeromepin** [comment]
I totally agree, it would be very nice to show how it can be used from the get go (either in the video or in the README).

I mean I installed it and have no idea how to use it 😅

**Comment by anuvyklack** [comment]
Just added new keybindng mechanism, which allowes to customise keybindings. You are welcome to check it.

**Comment by anuvyklack** [comment]
> I totally agree, it would be very nice to show how it can be used from the get go (either in the video or in the README).
> 
> I mean I installed it and have no idea how to use it sweat_smile

Just put cursor on closed fold and press `h`. Than again. Or press `h` and than `l`.

**Comment by jeromepin** [comment]
Thank you, it's very nice to have 💪 😃
