### ISSUE TITLE
Better matchup experience

### ISSUE THREAD

**Issue by ofseed** [anuvyklack/pretty-fold.nvim#23]
Could it possible to fold HTML tag
```html
<div>
  HTML tag
</div>
```

Like this:
```html
<div>...</div>
```

Maybe correctly defined matchup patterns could do it, but I don't know how to.

**Comment by ofseed** [comment]
Does it seem that the last element of the table which passed to the `matchup_patterns` is hardcoded to display?
![image](https://user-images.githubusercontent.com/61115159/172040206-15d06a78-4246-499e-9523-cbc078f4a953.png)

![image](https://user-images.githubusercontent.com/61115159/172040225-7d5767a3-2035-4b21-bc35-b14f4b46836f.png)

**Comment by anuvyklack** [comment]
Yes, the `matchup_patterns` is hardcoded. The treesitter is responding for the region to fold.
You can to tune what to fold in `treesitter/queries/html/folds.scm` file.
