### ISSUE TITLE
Way to suppress "preview module have been moved" message?

### ISSUE THREAD

**Issue by alxndr** [anuvyklack/pretty-fold.nvim#28]
When I start Neovim, I see this message in the status bar:

```
[pretty-fold.nvim] preview module have been moved into separate plugin:: https://github.com/anuvyklack/fold-preview.nvim
```

Is there a way to hide this message?

**Comment by anuvyklack** [comment]
Remove `require('pretty-fold').preview()` line somewhere inside you config.
