### ISSUE TITLE
Is there any way you can add the option for a border around the preview?

### ISSUE THREAD

**Issue by AndOrangutan** [anuvyklack/pretty-fold.nvim#8]
![2022-01-09_01-58](https://user-images.githubusercontent.com/40435989/148677634-8a1808ea-8143-4f08-98a6-f4eca58a0e57.png)

Basically just the title. It would be amazing if I could have a border,

![2022-01-09_02-01](https://user-images.githubusercontent.com/40435989/148677656-54b850f2-33cd-4ab5-84f0-fc5caaa540b7.png)

**Comment by anuvyklack** [comment]
Done in a3afa6ad21c34884390dec8ed0f0718f605e23b7

**Comment by AndOrangutan** [comment]
Sorry for the delay, just wanted to say thanks :D
